# Generated by Django 5.0.4 on 2025-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FDCSM', '0006_alter_fdc_pfs_info_pfs_tel_nbr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdc_pfs_info',
            name='PFS_NUM_AST',
            field=models.IntegerField(default=0, verbose_name='应用统计专业可选人数'),
        ),
        migrations.AddField(
            model_name='fdc_pfs_info',
            name='PFS_NUM_NANO',
            field=models.IntegerField(default=0, verbose_name='纳米科学与工程专业可选人数'),
        ),
        migrations.AlterField(
            model_name='fdc_pfs_sel',
            name='STU_PRO',
            field=models.IntegerField(choices=[(0, '物理专业'), (1, '数学专业'), (2, '系统科学专业'), (3, '应用统计专业'), (4, '纳米科学与工程专业')], verbose_name='学生专业'),
        ),
        migrations.AlterField(
            model_name='fdc_stu_info',
            name='STU_PRO',
            field=models.IntegerField(choices=[(0, '物理专业'), (1, '数学专业'), (2, '系统科学专业'), (3, '应用统计专业'), (4, '纳米科学与工程专业')], verbose_name='专业'),
        ),
    ]
