# Generated by Django 5.0.4 on 2024-04-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FDCSM", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fdc_pfs_sel",
            name="STU_PRO",
            field=models.IntegerField(
                choices=[(0, "物理专业"), (1, "数学专业"), (2, "系统科学专业")],
                default=1,
                verbose_name="学生专业",
            ),
            preserve_default=False,
        ),
    ]
