# Generated by Django 5.0.4 on 2024-04-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FDCSM", "0003_fdc_pfs_info_pfs_tel_nbr_fdc_stu_intro_stu_tel_nbr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fdc_stu_intro",
            name="STU_TEL_NBR",
            field=models.CharField(max_length=21, verbose_name="电话号码"),
        ),
    ]
