# Generated by Django 5.0.4 on 2024-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FDCSM", "0002_fdc_pfs_sel_stu_pro"),
    ]

    operations = [
        migrations.AddField(
            model_name="fdc_pfs_info",
            name="PFS_TEL_NBR",
            field=models.CharField(
                default=18223161844, max_length=20, verbose_name="电话号码"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fdc_stu_intro",
            name="STU_TEL_NBR",
            field=models.CharField(default=1, max_length=20, verbose_name="电话号码"),
            preserve_default=False,
        ),
    ]
