# Generated by Django 5.0.4 on 2024-04-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FDCSM", "0005_remove_fdc_stu_intro_stu_tel_nbr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fdc_pfs_info",
            name="PFS_TEL_NBR",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="电话号码"
            ),
        ),
        migrations.AlterField(
            model_name="fdc_stu_info",
            name="STU_TEL_NBR",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="电话号码"
            ),
        ),
    ]
