# Generated by Django 5.0.4 on 2024-04-24 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FDC_ADM_INFO",
            fields=[
                (
                    "ADM_NBR",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="登录账号",
                    ),
                ),
                ("ADM_NAM", models.CharField(max_length=20, verbose_name="姓名")),
                ("ADM_PWD", models.CharField(max_length=20, verbose_name="登录密码")),
                (
                    "CAT_TIM",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="用户创建时间"
                    ),
                ),
                ("CHG_TIM", models.DateTimeField(auto_now=True, verbose_name="用户更新时间")),
            ],
            options={
                "verbose_name": "管理员基本信息表",
                "db_table": "FDC_ADM_INFO",
            },
        ),
        migrations.CreateModel(
            name="FDC_PFS_INFO",
            fields=[
                (
                    "PFS_NBR",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="登录号码",
                    ),
                ),
                ("PFS_NAM", models.CharField(max_length=20, verbose_name="姓名")),
                ("PFS_PWD", models.CharField(max_length=20, verbose_name="登录密码")),
                (
                    "PFS_INTRO",
                    models.TextField(blank=True, max_length=400, verbose_name="简介"),
                ),
                (
                    "PFS_NUM_MATH",
                    models.IntegerField(default=0, verbose_name="数学专业可选人数"),
                ),
                (
                    "PFS_NUM_PSC",
                    models.IntegerField(default=0, verbose_name="物理专业可选人数"),
                ),
                (
                    "PFS_NUM_SCI",
                    models.IntegerField(default=0, verbose_name="系统科学专业可选人数"),
                ),
                (
                    "CAT_TIM",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="用户创建时间"
                    ),
                ),
                ("CHG_TIM", models.DateTimeField(auto_now=True, verbose_name="用户更新时间")),
            ],
            options={
                "verbose_name": "导师基本信息表",
                "db_table": "FDC_PFS_INFO",
            },
        ),
        migrations.CreateModel(
            name="FDC_STAT_INFO",
            fields=[
                (
                    "STAT_ID",
                    models.IntegerField(
                        choices=[
                            (0, "学生选择状态"),
                            (1, "导师选择第一志愿"),
                            (2, "导师选择第二志愿"),
                            (3, "导师选择第三志愿"),
                        ],
                        primary_key=True,
                        serialize=False,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "CAT_TIM",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="用户创建时间"
                    ),
                ),
                ("CHG_TIM", models.DateTimeField(auto_now=True, verbose_name="用户更新时间")),
            ],
            options={
                "verbose_name": "状态信息表",
                "db_table": "FDC_STAT_INFO",
            },
        ),
        migrations.CreateModel(
            name="FDC_STU_INFO",
            fields=[
                (
                    "STU_NBR",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="登录账号",
                    ),
                ),
                ("STU_PWD", models.CharField(max_length=20, verbose_name="登录密码")),
                ("STU_NAM", models.CharField(max_length=20, verbose_name="姓名")),
                (
                    "STU_PRO",
                    models.IntegerField(
                        choices=[(0, "物理专业"), (1, "数学专业"), (2, "系统科学专业")],
                        verbose_name="专业",
                    ),
                ),
                (
                    "STU_TYP",
                    models.IntegerField(
                        choices=[(0, "未被导师录取"), (1, "已被导师录取")],
                        default=0,
                        verbose_name="状态",
                    ),
                ),
                (
                    "CAT_TIM",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="用户创建时间"
                    ),
                ),
                ("CHG_TIM", models.DateTimeField(auto_now=True, verbose_name="用户更新时间")),
            ],
            options={
                "verbose_name": "学生基本信息表",
                "db_table": "FDC_STU_INFO",
            },
        ),
        migrations.CreateModel(
            name="FDC_PFS_SEL",
            fields=[
                ("SELECT_ID", models.AutoField(primary_key=True, serialize=False)),
                ("PFS_STATE", models.IntegerField(default=0, verbose_name="当前状态")),
                (
                    "CAT_TIM",
                    models.DateTimeField(auto_now_add=True, verbose_name="用户创建时间"),
                ),
                ("CHG_TIM", models.DateTimeField(auto_now=True, verbose_name="用户更新时间")),
                (
                    "PFS_NBR",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FDCSM.fdc_pfs_info",
                    ),
                ),
                (
                    "PFS_STU_NBR",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="PFS_STU_NBR",
                        to="FDCSM.fdc_stu_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "导师选择结果表",
                "db_table": "FDC_PFS_SEL",
            },
        ),
        migrations.CreateModel(
            name="FDC_STU_INTRO",
            fields=[
                (
                    "STU_NBR",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="FDCSM.fdc_stu_info",
                    ),
                ),
                (
                    "STU_GRADE",
                    models.FileField(
                        blank=True, null=True, upload_to="grade/", verbose_name="成绩"
                    ),
                ),
                (
                    "STU_VIT",
                    models.FileField(
                        blank=True, null=True, upload_to="intro/", verbose_name="简历"
                    ),
                ),
                (
                    "CAT_TIM",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="用户创建时间"
                    ),
                ),
                ("CHG_TIM", models.DateTimeField(auto_now=True, verbose_name="用户更新时间")),
                (
                    "STU_ONE_SEL",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="STU_ONE_SEL",
                        to="FDCSM.fdc_pfs_info",
                    ),
                ),
                (
                    "STU_THR_SEL",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="STU_THR_SEL",
                        to="FDCSM.fdc_pfs_info",
                    ),
                ),
                (
                    "STU_TOW_SEL",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="STU_TOW_SEL",
                        to="FDCSM.fdc_pfs_info",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生成绩、简历和志愿选择",
                "db_table": "FDC_STU_INTRO",
            },
        ),
    ]
